/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "src/accumulator.v:3.1-36.10" *)
module accumulator(clk, rst_n, clear, en, overflow_wrap, data_in, data_out);
  (* src = "src/accumulator.v:22.5-34.8" *)
  wire [31:0] _00_;
  (* src = "src/accumulator.v:20.22-20.49" *)
  wire _01_;
  (* src = "src/accumulator.v:28.17-28.43" *)
  wire _02_;
  (* src = "src/accumulator.v:28.29-28.43" *)
  wire _03_;
  (* src = "src/accumulator.v:20.55-20.78" *)
  wire _04_;
  wire [31:0] _05_;
  wire [31:0] _06_;
  wire [31:0] _07_;
  (* src = "src/accumulator.v:29.29-29.71" *)
  wire [31:0] _08_;
  (* src = "src/accumulator.v:6.24-6.29" *)
  input clear;
  wire clear;
  (* src = "src/accumulator.v:4.24-4.27" *)
  input clk;
  wire clk;
  (* src = "src/accumulator.v:9.24-9.31" *)
  input [31:0] data_in;
  wire [31:0] data_in;
  (* src = "src/accumulator.v:10.24-10.32" *)
  output [31:0] data_out;
  reg [31:0] data_out;
  (* src = "src/accumulator.v:7.24-7.26" *)
  input en;
  wire en;
  (* src = "src/accumulator.v:20.10-20.18" *)
  wire overflow;
  (* src = "src/accumulator.v:8.24-8.37" *)
  input overflow_wrap;
  wire overflow_wrap;
  (* src = "src/accumulator.v:5.24-5.29" *)
  input rst_n;
  wire rst_n;
  (* src = "src/accumulator.v:17.17-17.20" *)
  wire [31:0] sum;
  (* src = "src/accumulator.v:15.24-15.32" *)
  (* unused_bits = "32" *)
  wire [32:0] sum_full;
  assign sum = $signed(data_out) + (* src = "src/accumulator.v:15.35-15.102" *) $signed(data_in);
  assign _01_ = data_out[31] == (* src = "src/accumulator.v:20.22-20.49" *) data_in[31];
  assign overflow = _01_ && (* src = "src/accumulator.v:20.21-20.79" *) _04_;
  assign _02_ = overflow && (* src = "src/accumulator.v:28.17-28.43" *) _03_;
  assign _03_ = ! (* src = "src/accumulator.v:28.29-28.43" *) overflow_wrap;
  assign _04_ = sum[31] != (* src = "src/accumulator.v:20.55-20.78" *) data_out[31];
  (* src = "src/accumulator.v:22.5-34.8" *)
  always @(posedge clk)
    data_out <= _00_;
  assign _05_ = _02_ ? (* full_case = 32'd1 *) (* src = "src/accumulator.v:28.17-28.43|src/accumulator.v:28.13-32.16" *) _08_ : sum;
  assign _06_ = en ? (* src = "src/accumulator.v:27.22-27.24|src/accumulator.v:27.18-33.12" *) _05_ : data_out;
  assign _07_ = clear ? (* full_case = 32'd1 *) (* src = "src/accumulator.v:25.22-25.27|src/accumulator.v:25.18-33.12" *) 32'd0 : _06_;
  assign _00_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/accumulator.v:23.13-23.19|src/accumulator.v:23.9-33.12" *) _07_ : 32'd0;
  assign _08_ = data_out[31] ? (* src = "src/accumulator.v:29.29-29.71" *) 32'd2147483648 : 32'd2147483647;
  assign sum_full[31:0] = sum;
endmodule

(* src = "src/fp8_aligner.v:3.1-106.10" *)
module fp8_aligner(prod, exp_sum, sign, round_mode, overflow_wrap, aligned);
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire [63:0] _000_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire _001_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire _002_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire [63:0] _003_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire _004_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire [31:0] _005_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire _006_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire [63:0] _007_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire _008_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire [31:0] _009_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire _010_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire [63:0] _011_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire [63:0] _012_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire [63:0] _013_;
  (* src = "src/fp8_aligner.v:21.5-104.8" *)
  wire [63:0] _014_;
  (* src = "src/fp8_aligner.v:75.69-75.81" *)
  wire [63:0] _015_;
  (* src = "src/fp8_aligner.v:67.32-67.68" *)
  wire [63:0] _016_;
  (* src = "src/fp8_aligner.v:40.13-40.27" *)
  wire _017_;
  (* src = "src/fp8_aligner.v:43.21-43.41" *)
  wire _018_;
  (* src = "src/fp8_aligner.v:57.17-57.29" *)
  wire _019_;
  (* src = "src/fp8_aligner.v:63.30-63.35" *)
  wire _020_;
  (* src = "src/fp8_aligner.v:64.21-64.26" *)
  wire _021_;
  (* src = "src/fp8_aligner.v:75.35-75.65" *)
  wire _022_;
  (* src = "src/fp8_aligner.v:76.35-76.64" *)
  wire _023_;
  (* src = "src/fp8_aligner.v:93.64-93.93" *)
  wire _024_;
  (* src = "src/fp8_aligner.v:93.17-93.95" *)
  wire _025_;
  (* src = "src/fp8_aligner.v:99.17-99.60" *)
  wire _026_;
  (* src = "src/fp8_aligner.v:75.35-75.40" *)
  wire _027_;
  (* src = "src/fp8_aligner.v:93.17-93.31" *)
  wire _028_;
  (* src = "src/fp8_aligner.v:75.45-75.64" *)
  wire _029_;
  (* src = "src/fp8_aligner.v:79.29-79.46" *)
  wire _030_;
  (* src = "src/fp8_aligner.v:93.36-93.59" *)
  wire _031_;
  (* src = "src/fp8_aligner.v:93.36-93.94" *)
  wire _032_;
  (* src = "src/fp8_aligner.v:99.36-99.59" *)
  wire _033_;
  (* src = "src/fp8_aligner.v:45.25-45.44" *)
  wire _034_;
  (* src = "src/fp8_aligner.v:42.17-42.30" *)
  wire _035_;
  (* src = "src/fp8_aligner.v:49.25-49.48" *)
  wire _036_;
  (* src = "src/fp8_aligner.v:56.17-56.27" *)
  wire [10:0] _037_;
  (* src = "src/fp8_aligner.v:96.27-96.41" *)
  wire [31:0] _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire [63:0] _045_;
  (* src = "src/fp8_aligner.v:67.30-67.69" *)
  wire _046_;
  (* src = "src/fp8_aligner.v:93.44-93.59" *)
  wire _047_;
  (* src = "src/fp8_aligner.v:93.79-93.93" *)
  wire _048_;
  (* src = "src/fp8_aligner.v:99.44-99.59" *)
  wire _049_;
  (* src = "src/fp8_aligner.v:0.0-0.0" *)
  wire _050_;
  (* src = "src/fp8_aligner.v:45.56-45.76" *)
  wire [63:0] _051_;
  (* src = "src/fp8_aligner.v:67.44-67.58" *)
  wire [63:0] _052_;
  (* src = "src/fp8_aligner.v:62.24-62.36" *)
  wire [63:0] _053_;
  (* src = "src/fp8_aligner.v:63.47-63.50" *)
  wire [31:0] _054_;
  (* src = "src/fp8_aligner.v:67.43-67.67" *)
  wire [63:0] _055_;
  (* src = "src/fp8_aligner.v:63.29-63.58" *)
  wire _056_;
  (* src = "src/fp8_aligner.v:75.34-75.88" *)
  wire [63:0] _057_;
  (* src = "src/fp8_aligner.v:76.34-76.87" *)
  wire [63:0] _058_;
  (* src = "src/fp8_aligner.v:28.13-28.17" *)
  wire \align_logic.huge ;
  (* src = "src/fp8_aligner.v:24.20-24.27" *)
  wire [63:0] \align_logic.rounded ;
  (* src = "src/fp8_aligner.v:22.20-22.27" *)
  wire [63:0] \align_logic.shifted ;
  (* src = "src/fp8_aligner.v:9.24-9.31" *)
  output [31:0] aligned;
  wire [31:0] aligned;
  (* src = "src/fp8_aligner.v:5.30-5.37" *)
  input [9:0] exp_sum;
  wire [9:0] exp_sum;
  (* src = "src/fp8_aligner.v:8.24-8.37" *)
  input overflow_wrap;
  wire overflow_wrap;
  (* src = "src/fp8_aligner.v:4.24-4.28" *)
  input [31:0] prod;
  wire [31:0] prod;
  (* src = "src/fp8_aligner.v:7.24-7.34" *)
  input [1:0] round_mode;
  wire [1:0] round_mode;
  (* src = "src/fp8_aligner.v:19.24-19.33" *)
  wire [10:0] shift_amt;
  (* src = "src/fp8_aligner.v:6.24-6.28" *)
  input sign;
  wire sign;
  assign _015_ = _000_ + (* src = "src/fp8_aligner.v:75.69-75.81" *) 1'h1;
  assign _016_ = prod & (* src = "src/fp8_aligner.v:67.32-67.68" *) _055_;
  assign _017_ = $signed(shift_amt) >= (* src = "src/fp8_aligner.v:40.13-40.27" *) $signed(1'h0);
  assign _018_ = $signed(shift_amt) >= (* src = "src/fp8_aligner.v:43.21-43.41" *) $signed(6'h1f);
  assign _019_ = $signed(_037_) >= (* src = "src/fp8_aligner.v:57.17-57.29" *) $signed(8'h40);
  assign _020_ = $signed(_037_) > (* src = "src/fp8_aligner.v:63.30-63.35" *) $signed(1'h0);
  assign _021_ = $signed(_037_) > (* src = "src/fp8_aligner.v:64.21-64.26" *) $signed(2'h1);
  assign _022_ = _027_ && (* src = "src/fp8_aligner.v:75.35-75.65" *) _029_;
  assign _023_ = sign && (* src = "src/fp8_aligner.v:76.35-76.64" *) _029_;
  assign _024_ = \align_logic.rounded [31] && (* src = "src/fp8_aligner.v:93.64-93.93" *) _048_;
  assign _025_ = _028_ && (* src = "src/fp8_aligner.v:93.17-93.95" *) _032_;
  assign _026_ = _028_ && (* src = "src/fp8_aligner.v:99.17-99.60" *) _033_;
  assign _027_ = ! (* src = "src/fp8_aligner.v:75.35-75.40" *) sign;
  assign _028_ = ! (* src = "src/fp8_aligner.v:93.17-93.31" *) overflow_wrap;
  assign _029_ = _002_ || (* src = "src/fp8_aligner.v:75.45-75.64" *) _004_;
  assign _030_ = _004_ || (* src = "src/fp8_aligner.v:79.29-79.46" *) _000_[0];
  assign _031_ = \align_logic.huge  || (* src = "src/fp8_aligner.v:93.36-93.59" *) _047_;
  assign _032_ = _031_ || (* src = "src/fp8_aligner.v:93.36-93.94" *) _024_;
  assign _033_ = \align_logic.huge  || (* src = "src/fp8_aligner.v:99.36-99.59" *) _049_;
  assign _034_ = $signed(shift_amt) < (* src = "src/fp8_aligner.v:45.25-45.44" *) $signed(8'h40);
  assign _035_ = | (* src = "src/fp8_aligner.v:42.17-42.30" *) prod;
  assign _036_ = | (* src = "src/fp8_aligner.v:49.25-49.48" *) _051_[63:31];
  assign _037_ = - (* src = "src/fp8_aligner.v:56.17-56.27" *) $signed(shift_amt);
  assign _038_ = - (* src = "src/fp8_aligner.v:96.27-96.41" *) \align_logic.rounded [31:0];
  assign _009_ = _026_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:99.17-99.60|src/fp8_aligner.v:99.13-102.41" *) 32'd2147483647 : \align_logic.rounded [31:0];
  assign _005_ = _025_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:93.17-93.95|src/fp8_aligner.v:93.13-96.42" *) 32'd2147483648 : _038_;
  assign aligned = sign ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:91.13-91.17|src/fp8_aligner.v:91.9-103.12" *) _005_ : _009_;
  assign _014_ = _030_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:79.29-79.46|src/fp8_aligner.v:79.25-80.45" *) _015_ : _000_;
  assign _039_ = round_mode == (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:0.0-0.0|src/fp8_aligner.v:73.13-86.20" *) 2'h3;
  assign _013_ = _002_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:78.25-78.34|src/fp8_aligner.v:78.21-83.24" *) _014_ : _000_;
  function [63:0] _089_;
    input [63:0] a;
    input [255:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/fp8_aligner.v:0.0-0.0|src/fp8_aligner.v:73.13-86.20" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _089_ = b[63:0];
      4'b??1?:
        _089_ = b[127:64];
      4'b?1??:
        _089_ = b[191:128];
      4'b1???:
        _089_ = b[255:192];
      default:
        _089_ = a;
    endcase
  endfunction
  assign _012_ = _089_(64'hxxxxxxxxxxxxxxxx, { _000_, _057_, _058_, _013_ }, { _042_, _041_, _040_, _039_ });
  assign _040_ = round_mode == (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:0.0-0.0|src/fp8_aligner.v:73.13-86.20" *) 2'h2;
  assign _041_ = round_mode == (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:0.0-0.0|src/fp8_aligner.v:73.13-86.20" *) 1'h1;
  assign _042_ = ! (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:0.0-0.0|src/fp8_aligner.v:73.13-86.20" *) round_mode;
  assign _008_ = _021_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:64.21-64.26|src/fp8_aligner.v:64.17-70.20" *) _046_ : 1'h0;
  assign _043_ = _019_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:57.17-57.29|src/fp8_aligner.v:57.13-71.16" *) 1'h0 : _056_;
  assign _002_ = _017_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:40.13-40.27|src/fp8_aligner.v:40.9-87.12" *) 1'hx : _043_;
  assign _044_ = _019_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:57.17-57.29|src/fp8_aligner.v:57.13-71.16" *) _035_ : _008_;
  assign _004_ = _017_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:40.13-40.27|src/fp8_aligner.v:40.9-87.12" *) 1'hx : _044_;
  assign _045_ = _019_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:57.17-57.29|src/fp8_aligner.v:57.13-71.16" *) 64'h0000000000000000 : _053_;
  assign _000_ = _017_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:40.13-40.27|src/fp8_aligner.v:40.9-87.12" *) 64'hxxxxxxxxxxxxxxxx : _045_;
  assign _010_ = _036_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:49.25-49.48|src/fp8_aligner.v:49.21-49.62" *) 1'h1 : 1'h0;
  assign _011_ = _034_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:45.25-45.44|src/fp8_aligner.v:45.21-46.42" *) _051_ : 64'h0000000000000000;
  assign _007_ = _018_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:43.21-43.41|src/fp8_aligner.v:43.17-50.20" *) _011_ : _051_;
  assign _006_ = _018_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:43.21-43.41|src/fp8_aligner.v:43.17-50.20" *) 1'h1 : _010_;
  assign _001_ = _035_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:42.17-42.30|src/fp8_aligner.v:42.13-51.16" *) _006_ : 1'h0;
  assign _003_ = _035_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:42.17-42.30|src/fp8_aligner.v:42.13-51.16" *) _007_ : 64'h0000000000000000;
  assign \align_logic.huge  = _017_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:40.13-40.27|src/fp8_aligner.v:40.9-87.12" *) _001_ : 1'h0;
  assign \align_logic.rounded  = _017_ ? (* full_case = 32'd1 *) (* src = "src/fp8_aligner.v:40.13-40.27|src/fp8_aligner.v:40.9-87.12" *) _003_ : _012_;
  assign _046_ = | (* src = "src/fp8_aligner.v:67.30-67.69" *) _016_;
  assign _047_ = | (* src = "src/fp8_aligner.v:93.44-93.59" *) \align_logic.rounded [63:32];
  assign _048_ = | (* src = "src/fp8_aligner.v:93.79-93.93" *) \align_logic.rounded [30:0];
  assign _049_ = | (* src = "src/fp8_aligner.v:99.44-99.59" *) \align_logic.rounded [63:31];
  wire [63:0] _122_ = { 32'h00000000, prod };
  assign _050_ = _122_[$signed({ _054_[31], _054_[10:0] }) +: 1];
  assign _051_ = prod << (* src = "src/fp8_aligner.v:45.56-45.76" *) shift_amt;
  assign _052_ = 1'h1 << (* src = "src/fp8_aligner.v:67.44-67.58" *) { _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[10:0] };
  assign _053_ = prod >> (* src = "src/fp8_aligner.v:62.24-62.36" *) _037_;
  assign shift_amt = $signed(exp_sum) - (* src = "src/fp8_aligner.v:19.36-19.61" *) $signed(4'h5);
  assign { _054_[31], _054_[10:0] } = $signed(_037_) - (* src = "src/fp8_aligner.v:63.47-63.50" *) $signed(2'h1);
  assign _055_ = _052_ - (* src = "src/fp8_aligner.v:67.43-67.67" *) 1'h1;
  assign _056_ = _020_ ? (* src = "src/fp8_aligner.v:63.29-63.58" *) _050_ : 1'h0;
  assign _057_ = _022_ ? (* src = "src/fp8_aligner.v:75.34-75.88" *) _015_ : _000_;
  assign _058_ = _023_ ? (* src = "src/fp8_aligner.v:76.34-76.87" *) _015_ : _000_;
  assign _054_[30:11] = { _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31], _054_[31] };
  assign \align_logic.shifted  = { 32'h00000000, prod };
endmodule

(* src = "src/fp8_mul.v:3.1-179.10" *)
module fp8_mul(a, b, format_a, format_b, prod, exp_sum, sign);
  wire [5:0] _000_;
  (* src = "src/fp8_mul.v:172.68-172.101" *)
  wire [6:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  (* src = "src/fp8_mul.v:105.27-105.37" *)
  wire _012_;
  (* src = "src/fp8_mul.v:116.27-116.37" *)
  wire _013_;
  (* src = "src/fp8_mul.v:123.27-123.37" *)
  wire _014_;
  (* src = "src/fp8_mul.v:130.27-130.37" *)
  wire _015_;
  (* src = "src/fp8_mul.v:137.27-137.37" *)
  wire _016_;
  (* src = "src/fp8_mul.v:144.27-144.37" *)
  wire _017_;
  (* src = "src/fp8_mul.v:151.27-151.36" *)
  wire _018_;
  (* src = "src/fp8_mul.v:155.23-155.33" *)
  wire _019_;
  (* src = "src/fp8_mul.v:63.27-63.37" *)
  wire _020_;
  (* src = "src/fp8_mul.v:70.27-70.37" *)
  wire _021_;
  (* src = "src/fp8_mul.v:77.27-77.37" *)
  wire _022_;
  (* src = "src/fp8_mul.v:84.27-84.37" *)
  wire _023_;
  (* src = "src/fp8_mul.v:91.27-91.36" *)
  wire _024_;
  (* src = "src/fp8_mul.v:95.23-95.33" *)
  wire _025_;
  (* src = "src/fp8_mul.v:170.18-170.34" *)
  wire _026_;
  (* src = "src/fp8_mul.v:170.47-170.54" *)
  wire [15:0] _027_;
  (* src = "src/fp8_mul.v:148.29-148.31" *)
  wire [7:0] _028_;
  (* src = "src/fp8_mul.v:88.29-88.31" *)
  wire [7:0] _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  (* src = "src/fp8_mul.v:172.68-172.109" *)
  wire [6:0] _042_;
  (* src = "src/fp8_mul.v:148.22-148.35" *)
  wire [7:0] _043_;
  (* src = "src/fp8_mul.v:155.22-155.61" *)
  wire [7:0] _044_;
  (* src = "src/fp8_mul.v:88.22-88.35" *)
  wire [7:0] _045_;
  (* src = "src/fp8_mul.v:95.22-95.61" *)
  wire [7:0] _046_;
  (* src = "src/fp8_mul.v:4.23-4.24" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "src/fp8_mul.v:5.23-5.24" *)
  input [7:0] b;
  wire [7:0] b;
  wire [3:0] bias_a;
  wire [3:0] bias_b;
  (* src = "src/fp8_mul.v:22.15-22.17" *)
  wire [4:0] ea;
  (* src = "src/fp8_mul.v:22.19-22.21" *)
  wire [4:0] eb;
  (* src = "src/fp8_mul.v:9.30-9.37" *)
  output [6:0] exp_sum;
  wire [6:0] exp_sum;
  (* src = "src/fp8_mul.v:28.22-28.33" *)
  wire [6:0] exp_sum_res;
  (* src = "src/fp8_mul.v:6.23-6.31" *)
  input [2:0] format_a;
  wire [2:0] format_a;
  (* src = "src/fp8_mul.v:7.23-7.31" *)
  input [2:0] format_b;
  wire [2:0] format_b;
  (* src = "src/fp8_mul.v:23.15-23.17" *)
  wire [7:0] ma;
  (* src = "src/fp8_mul.v:23.19-23.21" *)
  wire [7:0] mb;
  (* src = "src/fp8_mul.v:27.16-27.21" *)
  wire [15:0] p_res;
  (* src = "src/fp8_mul.v:8.24-8.28" *)
  output [15:0] prod;
  wire [15:0] prod;
  (* src = "src/fp8_mul.v:10.23-10.27" *)
  output sign;
  wire sign;
  (* src = "src/fp8_mul.v:21.9-21.15" *)
  wire sign_a;
  (* src = "src/fp8_mul.v:21.17-21.23" *)
  wire sign_b;
  (* src = "src/fp8_mul.v:29.9-29.17" *)
  wire sign_res;
  (* src = "src/fp8_mul.v:25.9-25.15" *)
  wire zero_a;
  (* src = "src/fp8_mul.v:25.17-25.23" *)
  wire zero_b;
  assign _000_ = ea + (* src = "src/fp8_mul.v:172.23-172.64" *) eb;
  assign _001_ = $signed({ 2'h0, bias_a }) + (* src = "src/fp8_mul.v:172.68-172.101" *) $signed({ 2'h0, bias_b });
  assign _003_ = | { _034_, _033_ };
  assign _005_ = | { _040_, _037_, _036_ };
  assign _006_ = | { _039_, _038_ };
  assign _002_ = | { _031_, _030_ };
  assign _007_ = | { _041_, _040_ };
  assign _008_ = | { _034_, _031_, _030_ };
  assign _009_ = | { _033_, _032_ };
  assign _004_ = | { _037_, _036_ };
  assign _010_ = | { _035_, _034_ };
  assign _011_ = | { _040_, _039_ };
  assign _012_ = ! (* src = "src/fp8_mul.v:105.27-105.37" *) a[6:3];
  assign _013_ = ! (* src = "src/fp8_mul.v:116.27-116.37" *) b[6:3];
  assign _014_ = ! (* src = "src/fp8_mul.v:123.27-123.37" *) b[6:2];
  assign _015_ = ! (* src = "src/fp8_mul.v:130.27-130.37" *) b[4:2];
  assign _016_ = ! (* src = "src/fp8_mul.v:137.27-137.37" *) b[4:3];
  assign _017_ = ! (* src = "src/fp8_mul.v:144.27-144.37" *) b[2:1];
  assign _018_ = ! (* src = "src/fp8_mul.v:151.27-151.36" *) b;
  assign _019_ = b == (* src = "src/fp8_mul.v:155.23-155.33" *) 8'h80;
  assign _020_ = ! (* src = "src/fp8_mul.v:63.27-63.37" *) a[6:2];
  assign _021_ = ! (* src = "src/fp8_mul.v:70.27-70.37" *) a[4:2];
  assign _022_ = ! (* src = "src/fp8_mul.v:77.27-77.37" *) a[4:3];
  assign _023_ = ! (* src = "src/fp8_mul.v:84.27-84.37" *) a[2:1];
  assign _024_ = ! (* src = "src/fp8_mul.v:91.27-91.36" *) a;
  assign _025_ = a == (* src = "src/fp8_mul.v:95.23-95.33" *) 8'h80;
  assign _026_ = zero_a || (* src = "src/fp8_mul.v:170.18-170.34" *) zero_b;
  assign _027_ = ma * (* src = "src/fp8_mul.v:170.47-170.54" *) mb;
  assign _028_ = - (* src = "src/fp8_mul.v:148.29-148.31" *) b;
  assign _029_ = - (* src = "src/fp8_mul.v:88.29-88.31" *) a;
  function [0:0] _077_;
    input [0:0] a;
    input [4:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:110.9-167.16" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _077_ = b[0:0];
      5'b???1?:
        _077_ = b[1:1];
      5'b??1??:
        _077_ = b[2:2];
      5'b?1???:
        _077_ = b[3:3];
      5'b1????:
        _077_ = b[4:4];
      default:
        _077_ = a;
    endcase
  endfunction
  assign zero_b = _077_(_013_, { _014_, _015_, _016_, _017_, _018_ }, { _035_, _034_, _033_, _032_, _002_ });
  assign _030_ = format_b == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:110.9-167.16" *) 3'h6;
  assign _031_ = format_b == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:110.9-167.16" *) 3'h5;
  assign _032_ = format_b == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:110.9-167.16" *) 3'h4;
  assign _033_ = format_b == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:110.9-167.16" *) 2'h3;
  assign _034_ = format_b == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:110.9-167.16" *) 2'h2;
  assign _035_ = format_b == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:110.9-167.16" *) 1'h1;
  function [3:0] _084_;
    input [3:0] a;
    input [11:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:110.9-167.16" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _084_ = b[3:0];
      3'b?1?:
        _084_ = b[7:4];
      3'b1??:
        _084_ = b[11:8];
      default:
        _084_ = a;
    endcase
  endfunction
  assign bias_b = _084_(4'h7, 12'hf13, { _035_, _009_, _008_ });
  function [7:0] _085_;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:110.9-167.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _085_ = b[7:0];
      4'b??1?:
        _085_ = b[15:8];
      4'b?1??:
        _085_ = b[23:16];
      4'b1???:
        _085_ = b[31:24];
      default:
        _085_ = a;
    endcase
  endfunction
  assign mb = _085_({ 5'h01, b[2:0] }, { 5'h01, b[1:0], 6'h01, b[0], 2'h0, _043_, _044_ }, { _010_, _032_, _031_, _030_ });
  function [4:0] _086_;
    input [4:0] a;
    input [24:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:110.9-167.16" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _086_ = b[4:0];
      5'b???1?:
        _086_ = b[9:5];
      5'b??1??:
        _086_ = b[14:10];
      5'b?1???:
        _086_ = b[19:15];
      5'b1????:
        _086_ = b[24:20];
      default:
        _086_ = a;
    endcase
  endfunction
  assign eb = _086_({ 1'h0, b[6:3] }, { b[6:2], 2'h0, b[4:2], 3'h0, b[4:3], 3'h0, b[2:1], 5'h00 }, { _035_, _034_, _033_, _032_, _002_ });
  function [0:0] _087_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:110.9-167.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _087_ = b[0:0];
      2'b1?:
        _087_ = b[1:1];
      default:
        _087_ = a;
    endcase
  endfunction
  assign sign_b = _087_(b[7], { b[5], b[3] }, { _003_, _032_ });
  function [0:0] _088_;
    input [0:0] a;
    input [4:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:50.9-107.16" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _088_ = b[0:0];
      5'b???1?:
        _088_ = b[1:1];
      5'b??1??:
        _088_ = b[2:2];
      5'b?1???:
        _088_ = b[3:3];
      5'b1????:
        _088_ = b[4:4];
      default:
        _088_ = a;
    endcase
  endfunction
  assign zero_a = _088_(_012_, { _020_, _021_, _022_, _023_, _024_ }, { _041_, _040_, _039_, _038_, _004_ });
  assign _036_ = format_a == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:50.9-107.16" *) 3'h6;
  assign _037_ = format_a == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:50.9-107.16" *) 3'h5;
  assign _038_ = format_a == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:50.9-107.16" *) 3'h4;
  assign _039_ = format_a == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:50.9-107.16" *) 2'h3;
  assign _040_ = format_a == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:50.9-107.16" *) 2'h2;
  assign _041_ = format_a == (* full_case = 32'd1 *) (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:50.9-107.16" *) 1'h1;
  function [3:0] _095_;
    input [3:0] a;
    input [11:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:50.9-107.16" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _095_ = b[3:0];
      3'b?1?:
        _095_ = b[7:4];
      3'b1??:
        _095_ = b[11:8];
      default:
        _095_ = a;
    endcase
  endfunction
  assign bias_a = _095_(4'h7, 12'hf13, { _041_, _006_, _005_ });
  function [7:0] _096_;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:50.9-107.16" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _096_ = b[7:0];
      4'b??1?:
        _096_ = b[15:8];
      4'b?1??:
        _096_ = b[23:16];
      4'b1???:
        _096_ = b[31:24];
      default:
        _096_ = a;
    endcase
  endfunction
  assign ma = _096_({ 5'h01, a[2:0] }, { 5'h01, a[1:0], 6'h01, a[0], 2'h0, _045_, _046_ }, { _007_, _038_, _037_, _036_ });
  function [4:0] _097_;
    input [4:0] a;
    input [24:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:50.9-107.16" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _097_ = b[4:0];
      5'b???1?:
        _097_ = b[9:5];
      5'b??1??:
        _097_ = b[14:10];
      5'b?1???:
        _097_ = b[19:15];
      5'b1????:
        _097_ = b[24:20];
      default:
        _097_ = a;
    endcase
  endfunction
  assign ea = _097_({ 1'h0, a[6:3] }, { a[6:2], 2'h0, a[4:2], 3'h0, a[4:3], 3'h0, a[2:1], 5'h00 }, { _041_, _040_, _039_, _038_, _004_ });
  function [0:0] _098_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/fp8_mul.v:0.0-0.0|src/fp8_mul.v:50.9-107.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _098_ = b[0:0];
      2'b1?:
        _098_ = b[1:1];
      default:
        _098_ = a;
    endcase
  endfunction
  assign sign_a = _098_(a[7], { a[5], a[3] }, { _011_, _038_ });
  assign _042_ = $signed(_001_) - (* src = "src/fp8_mul.v:172.68-172.109" *) $signed(4'h7);
  assign exp_sum = $signed({ 1'h0, _000_ }) - (* src = "src/fp8_mul.v:172.23-172.110" *) $signed(_042_);
  assign _043_ = b[7] ? (* src = "src/fp8_mul.v:148.22-148.35" *) _028_ : { 1'h0, b[6:0] };
  assign _044_ = _019_ ? (* src = "src/fp8_mul.v:155.22-155.61" *) 8'h7f : _043_;
  assign prod = _026_ ? (* src = "src/fp8_mul.v:170.17-170.55" *) 16'h0000 : _027_;
  assign _045_ = a[7] ? (* src = "src/fp8_mul.v:88.22-88.35" *) _029_ : { 1'h0, a[6:0] };
  assign _046_ = _025_ ? (* src = "src/fp8_mul.v:95.22-95.61" *) 8'h7f : _045_;
  assign sign = sign_a ^ (* src = "src/fp8_mul.v:171.20-171.35" *) sign_b;
  assign exp_sum_res = exp_sum;
  assign p_res = prod;
  assign sign_res = sign;
endmodule

(* top =  1  *)
(* src = "src/project.v:11.1-281.10" *)
module tt_um_chatelao_fp8_multiplier(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  (* src = "src/project.v:55.5-92.8" *)
  wire [5:0] _000_;
  (* src = "src/project.v:55.5-92.8" *)
  wire [2:0] _001_;
  (* src = "src/project.v:55.5-92.8" *)
  wire [2:0] _002_;
  (* src = "src/project.v:118.5-128.8" *)
  wire [6:0] _003_;
  (* src = "src/project.v:118.5-128.8" *)
  wire [15:0] _004_;
  (* src = "src/project.v:118.5-128.8" *)
  wire _005_;
  (* src = "src/project.v:55.5-92.8" *)
  wire _006_;
  (* src = "src/project.v:55.5-92.8" *)
  wire [1:0] _007_;
  (* src = "src/project.v:55.5-92.8" *)
  wire [7:0] _008_;
  (* src = "src/project.v:55.5-92.8" *)
  wire [7:0] _009_;
  (* src = "src/project.v:172.5-178.8" *)
  wire [31:0] _010_;
  (* src = "src/project.v:55.5-92.8" *)
  wire [1:0] _011_;
  (* src = "src/project.v:182.5-194.8" *)
  wire [7:0] _012_;
  wire [8:0] _013_;
  (* src = "src/project.v:141.67-141.86" *)
  wire [9:0] _014_;
  (* src = "src/project.v:71.64-71.82" *)
  wire [5:0] _015_;
  (* src = "src/project.v:156.72-156.93" *)
  wire _016_;
  (* src = "src/project.v:156.97-156.118" *)
  wire _017_;
  (* src = "src/project.v:175.29-175.49" *)
  wire _018_;
  (* src = "src/project.v:67.17-67.36" *)
  wire _019_;
  (* src = "src/project.v:71.33-71.53" *)
  wire _020_;
  (* src = "src/project.v:140.36-140.56" *)
  wire _021_;
  (* src = "src/project.v:156.23-156.42" *)
  wire _022_;
  (* src = "src/project.v:183.38-183.58" *)
  wire _023_;
  (* src = "src/project.v:156.46-156.66" *)
  wire _024_;
  (* src = "src/project.v:157.23-157.42" *)
  wire _025_;
  (* src = "src/project.v:156.23-156.66" *)
  wire _026_;
  (* src = "src/project.v:175.22-175.49" *)
  wire _027_;
  (* src = "src/project.v:183.13-183.58" *)
  wire _028_;
  (* src = "src/project.v:67.17-67.48" *)
  wire _029_;
  (* src = "src/project.v:156.72-156.118" *)
  wire _030_;
  (* src = "src/project.v:157.48-157.69" *)
  wire _031_;
  (* src = "src/project.v:137.41-137.49" *)
  wire [31:0] _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire [31:0] _036_;
  wire _037_;
  wire [6:0] _038_;
  wire [15:0] _039_;
  wire [7:0] _040_;
  wire _041_;
  wire [7:0] _042_;
  wire [7:0] _043_;
  wire [7:0] _044_;
  wire _045_;
  wire [7:0] _046_;
  wire [7:0] _047_;
  wire [5:0] _048_;
  wire [5:0] _049_;
  wire [1:0] _050_;
  wire _051_;
  wire [1:0] _052_;
  wire [1:0] _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire [1:0] _057_;
  wire [1:0] _058_;
  wire [1:0] _059_;
  wire [2:0] _060_;
  wire [2:0] _061_;
  wire [2:0] _062_;
  wire [2:0] _063_;
  wire [2:0] _064_;
  wire [2:0] _065_;
  (* src = "src/project.v:71.32-71.82" *)
  wire [5:0] _066_;
  (* src = "src/project.v:137.17-137.24" *)
  wire [31:0] acc_abs;
  (* src = "src/project.v:157.10-157.19" *)
  wire acc_clear;
  (* src = "src/project.v:156.10-156.16" *)
  wire acc_en;
  (* src = "src/project.v:136.17-136.24" *)
  wire [31:0] acc_out;
  (* src = "src/project.v:144.17-144.28" *)
  wire [31:0] aligned_res;
  (* src = "src/project.v:141.23-141.37" *)
  wire [9:0] aligner_in_exp;
  (* src = "src/project.v:140.17-140.32" *)
  wire [31:0] aligner_in_prod;
  (* src = "src/project.v:142.10-142.25" *)
  wire aligner_in_sign;
  (* keep = 32'd1 *)
  (* src = "src/project.v:18.34-18.37" *)
  input clk;
  wire clk;
  (* src = "src/project.v:29.15-29.26" *)
  reg [5:0] cycle_count = 6'h00;
  (* keep = 32'd1 *)
  (* src = "src/project.v:17.34-17.37" *)
  input ena;
  wire ena;
  (* src = "src/project.v:34.15-34.23" *)
  reg [2:0] format_a = 3'h0;
  (* src = "src/project.v:35.15-35.23" *)
  reg [2:0] format_b = 3'h0;
  (* src = "src/project.v:100.23-100.34" *)
  wire [6:0] mul_exp_sum;
  (* src = "src/project.v:115.22-115.37" *)
  reg [6:0] mul_exp_sum_reg;
  (* src = "src/project.v:99.17-99.25" *)
  wire [15:0] mul_prod;
  (* src = "src/project.v:114.16-114.28" *)
  reg [15:0] mul_prod_reg;
  (* src = "src/project.v:101.10-101.18" *)
  wire mul_sign;
  (* src = "src/project.v:116.9-116.21" *)
  reg mul_sign_reg;
  (* src = "src/project.v:37.15-37.28" *)
  reg overflow_wrap = 1'h0;
  (* src = "src/project.v:36.15-36.25" *)
  reg [1:0] round_mode = 2'h0;
  (* keep = 32'd1 *)
  (* src = "src/project.v:19.34-19.39" *)
  input rst_n;
  wire rst_n;
  (* src = "src/project.v:32.15-32.22" *)
  reg [7:0] scale_a = 8'h00;
  (* src = "src/project.v:33.15-33.22" *)
  reg [7:0] scale_b = 8'h00;
  (* src = "src/project.v:171.16-171.30" *)
  reg [31:0] scaled_acc_reg;
  (* src = "src/project.v:132.23-132.33" *)
  wire [9:0] shared_exp;
  (* src = "src/project.v:28.15-28.20" *)
  reg [1:0] state = 2'h0;
  (* src = "src/project.v:12.23-12.28" *)
  input [7:0] ui_in;
  wire [7:0] ui_in;
  (* src = "src/project.v:14.23-14.29" *)
  input [7:0] uio_in;
  wire [7:0] uio_in;
  (* src = "src/project.v:16.23-16.29" *)
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  (* src = "src/project.v:15.23-15.30" *)
  output [7:0] uio_out;
  wire [7:0] uio_out;
  (* src = "src/project.v:13.23-13.29" *)
  output [7:0] uo_out;
  wire [7:0] uo_out;
  (* src = "src/project.v:181.15-181.25" *)
  wire [7:0] uo_out_reg;
  assign _013_ = scale_a + (* src = "src/project.v:132.36-132.87" *) scale_b;
  assign _014_ = shared_exp + (* src = "src/project.v:141.67-141.86" *) 3'h5;
  assign _015_ = cycle_count + (* src = "src/project.v:71.64-71.82" *) 1'h1;
  assign _016_ = state == (* src = "src/project.v:156.72-156.93" *) 2'h2;
  assign _017_ = state == (* src = "src/project.v:156.97-156.118" *) 2'h3;
  assign _018_ = cycle_count == (* src = "src/project.v:175.29-175.49" *) 6'h24;
  assign _019_ = ! (* src = "src/project.v:67.17-67.36" *) state;
  assign _020_ = cycle_count == (* src = "src/project.v:71.33-71.53" *) 6'h28;
  assign _021_ = cycle_count >= (* src = "src/project.v:140.36-140.56" *) 6'h24;
  assign _022_ = cycle_count >= (* src = "src/project.v:156.23-156.42" *) 3'h4;
  assign _023_ = cycle_count >= (* src = "src/project.v:183.38-183.58" *) 6'h25;
  assign _024_ = cycle_count <= (* src = "src/project.v:156.46-156.66" *) 6'h23;
  assign _025_ = cycle_count <= (* src = "src/project.v:157.23-157.42" *) 2'h2;
  assign _026_ = _022_ && (* src = "src/project.v:156.23-156.66" *) _024_;
  assign acc_en = _026_ && (* src = "src/project.v:156.22-156.119" *) _030_;
  assign acc_clear = _025_ && (* src = "src/project.v:157.22-157.70" *) _031_;
  assign _027_ = ena && (* src = "src/project.v:175.22-175.49" *) _018_;
  assign _028_ = _017_ && (* src = "src/project.v:183.13-183.58" *) _023_;
  assign _029_ = _019_ && (* src = "src/project.v:67.17-67.48" *) ui_in[7];
  assign _030_ = _016_ || (* src = "src/project.v:156.72-156.118" *) _017_;
  assign _031_ = state != (* src = "src/project.v:157.48-157.69" *) 2'h2;
  assign _032_ = - (* src = "src/project.v:137.41-137.49" *) acc_out;
  (* src = "src/project.v:172.5-178.8" *)
  always @(posedge clk)
    scaled_acc_reg <= _010_;
  (* src = "src/project.v:118.5-128.8" *)
  always @(posedge clk)
    mul_prod_reg <= _004_;
  (* src = "src/project.v:118.5-128.8" *)
  always @(posedge clk)
    mul_exp_sum_reg <= _003_;
  (* src = "src/project.v:118.5-128.8" *)
  always @(posedge clk)
    mul_sign_reg <= _005_;
  (* src = "src/project.v:55.5-92.8" *)
  always @(posedge clk)
    format_a <= _001_;
  (* src = "src/project.v:55.5-92.8" *)
  always @(posedge clk)
    format_b <= _002_;
  (* src = "src/project.v:55.5-92.8" *)
  always @(posedge clk)
    round_mode <= _007_;
  (* src = "src/project.v:55.5-92.8" *)
  always @(posedge clk)
    overflow_wrap <= _006_;
  (* src = "src/project.v:55.5-92.8" *)
  always @(posedge clk)
    state <= _011_;
  (* src = "src/project.v:55.5-92.8" *)
  always @(posedge clk)
    cycle_count <= _000_;
  (* src = "src/project.v:55.5-92.8" *)
  always @(posedge clk)
    scale_a <= _008_;
  (* src = "src/project.v:55.5-92.8" *)
  always @(posedge clk)
    scale_b <= _009_;
  function [7:0] _101_;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "src/project.v:0.0-0.0|src/project.v:184.13-190.20" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _101_ = b[7:0];
      4'b??1?:
        _101_ = b[15:8];
      4'b?1??:
        _101_ = b[23:16];
      4'b1???:
        _101_ = b[31:24];
      default:
        _101_ = a;
    endcase
  endfunction
  assign _012_ = _101_(8'h00, scaled_acc_reg, { _035_, _034_, _033_, _020_ });
  assign _033_ = cycle_count == (* full_case = 32'd1 *) (* src = "src/project.v:0.0-0.0|src/project.v:184.13-190.20" *) 6'h27;
  assign _034_ = cycle_count == (* full_case = 32'd1 *) (* src = "src/project.v:0.0-0.0|src/project.v:184.13-190.20" *) 6'h26;
  assign _035_ = cycle_count == (* full_case = 32'd1 *) (* src = "src/project.v:0.0-0.0|src/project.v:184.13-190.20" *) 6'h25;
  assign uo_out = _028_ ? (* full_case = 32'd1 *) (* src = "src/project.v:183.13-183.58|src/project.v:183.9-193.12" *) _012_ : 8'h00;
  assign _036_ = _027_ ? (* src = "src/project.v:175.22-175.49|src/project.v:175.18-177.12" *) aligned_res : scaled_acc_reg;
  assign _010_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:173.13-173.19|src/project.v:173.9-177.12" *) _036_ : 32'd0;
  assign _037_ = ena ? (* src = "src/project.v:123.22-123.25|src/project.v:123.18-127.12" *) mul_sign : mul_sign_reg;
  assign _005_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:119.13-119.19|src/project.v:119.9-127.12" *) _037_ : 1'h0;
  assign _038_ = ena ? (* src = "src/project.v:123.22-123.25|src/project.v:123.18-127.12" *) mul_exp_sum : mul_exp_sum_reg;
  assign _003_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:119.13-119.19|src/project.v:119.9-127.12" *) _038_ : 7'h00;
  assign _039_ = ena ? (* src = "src/project.v:123.22-123.25|src/project.v:123.18-127.12" *) mul_prod : mul_prod_reg;
  assign _004_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:119.13-119.19|src/project.v:119.9-127.12" *) _039_ : 16'h0000;
  assign _040_ = _041_ ? (* src = "src/project.v:0.0-0.0|src/project.v:73.17-89.24" *) uio_in : scale_b;
  assign _041_ = cycle_count == (* src = "src/project.v:0.0-0.0|src/project.v:73.17-89.24" *) 2'h2;
  assign _042_ = _029_ ? (* full_case = 32'd1 *) (* src = "src/project.v:67.17-67.48|src/project.v:67.13-90.16" *) scale_b : _040_;
  assign _043_ = ena ? (* src = "src/project.v:65.22-65.25|src/project.v:65.18-91.12" *) _042_ : scale_b;
  assign _009_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:56.13-56.19|src/project.v:56.9-91.12" *) _043_ : 8'h00;
  assign _044_ = _045_ ? (* src = "src/project.v:0.0-0.0|src/project.v:73.17-89.24" *) ui_in : scale_a;
  assign _045_ = cycle_count == (* src = "src/project.v:0.0-0.0|src/project.v:73.17-89.24" *) 1'h1;
  assign _046_ = _029_ ? (* full_case = 32'd1 *) (* src = "src/project.v:67.17-67.48|src/project.v:67.13-90.16" *) scale_a : _044_;
  assign _047_ = ena ? (* src = "src/project.v:65.22-65.25|src/project.v:65.18-91.12" *) _046_ : scale_a;
  assign _008_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:56.13-56.19|src/project.v:56.9-91.12" *) _047_ : 8'h00;
  assign _048_ = _029_ ? (* full_case = 32'd1 *) (* src = "src/project.v:67.17-67.48|src/project.v:67.13-90.16" *) 6'h03 : _066_;
  assign _049_ = ena ? (* src = "src/project.v:65.22-65.25|src/project.v:65.18-91.12" *) _048_ : cycle_count;
  assign _000_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:56.13-56.19|src/project.v:56.9-91.12" *) _049_ : 6'h00;
  function [1:0] _127_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* src = "src/project.v:0.0-0.0|src/project.v:73.17-89.24" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _127_ = b[1:0];
      4'b??1?:
        _127_ = b[3:2];
      4'b?1??:
        _127_ = b[5:4];
      4'b1???:
        _127_ = b[7:6];
      default:
        _127_ = a;
    endcase
  endfunction
  assign _050_ = _127_(state, 8'h6c, { _051_, _041_, _018_, _020_ });
  assign _051_ = ! (* src = "src/project.v:0.0-0.0|src/project.v:73.17-89.24" *) cycle_count;
  assign _052_ = _029_ ? (* full_case = 32'd1 *) (* src = "src/project.v:67.17-67.48|src/project.v:67.13-90.16" *) 2'h2 : _050_;
  assign _053_ = ena ? (* src = "src/project.v:65.22-65.25|src/project.v:65.18-91.12" *) _052_ : state;
  assign _011_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:56.13-56.19|src/project.v:56.9-91.12" *) _053_ : 2'h0;
  assign _054_ = _045_ ? (* src = "src/project.v:0.0-0.0|src/project.v:73.17-89.24" *) uio_in[5] : overflow_wrap;
  assign _055_ = _029_ ? (* full_case = 32'd1 *) (* src = "src/project.v:67.17-67.48|src/project.v:67.13-90.16" *) overflow_wrap : _054_;
  assign _056_ = ena ? (* src = "src/project.v:65.22-65.25|src/project.v:65.18-91.12" *) _055_ : overflow_wrap;
  assign _006_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:56.13-56.19|src/project.v:56.9-91.12" *) _056_ : 1'h0;
  assign _057_ = _045_ ? (* src = "src/project.v:0.0-0.0|src/project.v:73.17-89.24" *) uio_in[4:3] : round_mode;
  assign _058_ = _029_ ? (* full_case = 32'd1 *) (* src = "src/project.v:67.17-67.48|src/project.v:67.13-90.16" *) round_mode : _057_;
  assign _059_ = ena ? (* src = "src/project.v:65.22-65.25|src/project.v:65.18-91.12" *) _058_ : round_mode;
  assign _007_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:56.13-56.19|src/project.v:56.9-91.12" *) _059_ : 2'h0;
  assign _060_ = _041_ ? (* src = "src/project.v:0.0-0.0|src/project.v:73.17-89.24" *) ui_in[2:0] : format_b;
  assign _061_ = _029_ ? (* full_case = 32'd1 *) (* src = "src/project.v:67.17-67.48|src/project.v:67.13-90.16" *) format_b : _060_;
  assign _062_ = ena ? (* src = "src/project.v:65.22-65.25|src/project.v:65.18-91.12" *) _061_ : format_b;
  assign _002_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:56.13-56.19|src/project.v:56.9-91.12" *) _062_ : 3'h0;
  assign _063_ = _045_ ? (* src = "src/project.v:0.0-0.0|src/project.v:73.17-89.24" *) uio_in[2:0] : format_a;
  assign _064_ = _029_ ? (* full_case = 32'd1 *) (* src = "src/project.v:67.17-67.48|src/project.v:67.13-90.16" *) format_a : _063_;
  assign _065_ = ena ? (* src = "src/project.v:65.22-65.25|src/project.v:65.18-91.12" *) _064_ : format_a;
  assign _001_ = rst_n ? (* full_case = 32'd1 *) (* src = "src/project.v:56.13-56.19|src/project.v:56.9-91.12" *) _065_ : 3'h0;
  assign shared_exp = _013_ - (* src = "src/project.v:132.36-132.98" *) 8'hfe;
  assign acc_abs = acc_out[31] ? (* src = "src/project.v:137.27-137.59" *) _032_ : { 1'h0, acc_out[30:0] };
  assign aligner_in_prod = _021_ ? (* src = "src/project.v:140.35-140.91" *) acc_abs : { 16'h0000, mul_prod_reg };
  assign aligner_in_exp = _021_ ? (* src = "src/project.v:141.41-141.132" *) _014_ : { mul_exp_sum_reg[6], mul_exp_sum_reg[6], mul_exp_sum_reg[6], mul_exp_sum_reg };
  assign aligner_in_sign = _021_ ? (* src = "src/project.v:142.28-142.79" *) acc_out[31] : mul_sign_reg;
  assign _066_ = _020_ ? (* src = "src/project.v:71.32-71.82" *) 6'h00 : _015_;
  (* module_not_derived = 32'd1 *)
  (* src = "src/project.v:159.17-167.6" *)
  accumulator acc_inst (
    .clear(acc_clear),
    .clk(clk),
    .data_in(aligned_res),
    .data_out(acc_out),
    .en(acc_en),
    .overflow_wrap(overflow_wrap),
    .rst_n(rst_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/project.v:145.17-152.6" *)
  fp8_aligner aligner_inst (
    .aligned(aligned_res),
    .exp_sum(aligner_in_exp),
    .overflow_wrap(overflow_wrap),
    .prod(aligner_in_prod),
    .round_mode(round_mode),
    .sign(aligner_in_sign)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/project.v:103.13-111.6" *)
  fp8_mul multiplier (
    .a(ui_in),
    .b(uio_in),
    .exp_sum(mul_exp_sum),
    .format_a(format_a),
    .format_b(format_b),
    .prod(mul_prod),
    .sign(mul_sign)
  );
  assign uio_oe = 8'h00;
  assign uio_out = 8'h00;
  assign uo_out_reg = uo_out;
endmodule
