`ifndef __ACCUMULATOR_V__
`define __ACCUMULATOR_V__
`default_nettype none

/**
 * Accumulator Module
 *
 * This module is responsible for summing up the products generated by the MAC unit.
 * It is a fundamental part of the Multiply-Accumulate operation.
 */
module accumulator #(
    parameter WIDTH = 40 // The bit-width of the internal accumulation register.
)(
    input  wire        clk,           // System clock
    input  wire        rst_n,         // Active-low asynchronous reset
    input  wire        clear,         // Synchronous clear
    input  wire        en,            // Enable accumulation
    input  wire        overflow_wrap, // 1 = wrap, 0 = saturate
    input  wire [WIDTH-1:0] data_in,  // Aligned product
    input  wire        load_en,       // Load enable
    input  wire [WIDTH-1:0] load_data, // Value to be loaded
    input  wire        shift_en,      // Shift enable for serialization
    output wire [7:0]  shift_out,     // 8 bits out (MSB first)
    output wire [WIDTH-1:0] data_out  // Full current value
);

    reg [WIDTH-1:0] acc_reg;

    assign data_out  = acc_reg;
    // Always output the 8 most significant bits for serialization.
    assign shift_out = acc_reg[WIDTH-1:WIDTH-8];

    // Signed arithmetic: extend width by 1 bit to detect overflow.
    wire signed [WIDTH:0] sum_full = $signed({acc_reg[WIDTH-1], acc_reg}) + $signed({data_in[WIDTH-1], data_in});
    wire [WIDTH-1:0] sum = sum_full[WIDTH-1:0];

    // Overflow check
    wire overflow = (acc_reg[WIDTH-1] == data_in[WIDTH-1]) && (sum[WIDTH-1] != acc_reg[WIDTH-1]);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            acc_reg <= {WIDTH{1'b0}};
        end else if (clear) begin
            acc_reg <= {WIDTH{1'b0}};
        end else if (load_en) begin
            acc_reg <= load_data;
        end else if (shift_en) begin
            // Shift out 8 bits, filling with zeros from the right.
            acc_reg <= {acc_reg[WIDTH-9:0], 8'd0};
        end else if (en) begin
            if (overflow && !overflow_wrap) begin
                // Saturation
                acc_reg <= acc_reg[WIDTH-1] ? {1'b1, {(WIDTH-1){1'b0}}} : {1'b0, {(WIDTH-1){1'b1}}};
            end else begin
                // Wrapping
                acc_reg <= sum;
            end
        end
    end

endmodule
`endif
