`ifndef __ACCUMULATOR_V__
`define __ACCUMULATOR_V__
`default_nettype none

/**
 * Accumulator Module
 *
 * This module is responsible for summing up the products generated by the MAC unit.
 * It is a fundamental part of the Multiply-Accumulate operation.
 *
 * Beginner Note:
 * In Verilog, 'parameter' allows you to customize the module when you use it (instantiate it).
 * 'WIDTH' here determines how many bits the accumulator can hold.
 */
module accumulator #(
    parameter WIDTH = 40 // The bit-width of the internal accumulation register.
)(
    input  wire        clk,           // System clock: All operations happen on the rising edge.
    input  wire        rst_n,         // Active-low asynchronous reset: Returns the register to zero immediately.
    input  wire        clear,         // Synchronous clear: Resets the accumulator to zero on the next clock edge.
    input  wire        en,            // Enable accumulation: When high, the 'data_in' is added to the current total.
    input  wire        overflow_wrap, // Configurable overflow: 1 = wrap around (modulo), 0 = saturate (clamp to max/min).
    input  wire [WIDTH-1:0] data_in,  // The aligned product to be added to the current value.
    input  wire        load_en,       // Load enable: Used to set the register to a specific value (e.g., for initialization).
    input  wire [WIDTH-1:0] load_data, // The value to be loaded into the register.
    input  wire        shift_en,      // Shift enable: Used to shift the result out 8 bits at a time for serial output.
    output wire [7:0]  shift_out,     // The 8 most significant bits (MSB) of the register, used for serialization.
    output wire [WIDTH-1:0] data_out  // The current full value stored in the accumulator.
);

    // 'localparam' is a constant that is only visible inside this module.
    // We ensure REG_WIDTH is at least 32 bits to match 'load_data'.
    localparam REG_WIDTH = (WIDTH > 32) ? WIDTH : 32;

    // 'reg' is a Verilog data type that can hold a value. In this case, it will be synthesized into flip-flops.
    reg [REG_WIDTH-1:0] acc_reg;

    // 'assign' statements create combinational logic that continuously drives a wire.
    assign data_out  = acc_reg[WIDTH-1:0];
    assign shift_out = acc_reg[REG_WIDTH-1:REG_WIDTH-8];

    // Signed arithmetic: We extend the width by 1 bit to detect if an overflow occurred.
    // $signed() tells the simulator/synthesizer to treat the bits as 2's complement numbers.
    /* verilator lint_off UNUSEDSIGNAL */
    wire signed [WIDTH:0] sum_full = $signed({acc_reg[WIDTH-1], acc_reg[WIDTH-1:0]}) + $signed({data_in[WIDTH-1], data_in});
    /* verilator lint_on UNUSEDSIGNAL */

    // 'sum' is the standard result of the addition (which naturally wraps if it exceeds 'WIDTH').
    wire [WIDTH-1:0] sum = sum_full[WIDTH-1:0];

    // Overflow check: If the signs of the inputs are the same but the sign of the result is different.
    wire overflow = (acc_reg[WIDTH-1] == data_in[WIDTH-1]) && (sum[WIDTH-1] != acc_reg[WIDTH-1]);

    // This 'always' block describes sequential logic that updates on the rising edge of the clock
    // or the falling edge of the asynchronous reset.
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            // Reset: Asynchronous return to zero.
            acc_reg <= {REG_WIDTH{1'b0}};
        end else if (clear) begin
            // Clear: Synchronous return to zero.
            acc_reg <= {REG_WIDTH{1'b0}};
        end else if (load_en) begin
            // Load: Direct assignment from load_data.
            acc_reg <= {load_data, {(REG_WIDTH-WIDTH){1'b0}}};
        end else if (shift_en) begin
            // Shift: Move bits 8 positions to the left, filling with zeros from the right.
            acc_reg <= {acc_reg[REG_WIDTH-9:0], 8'd0};
        end else if (en) begin
            // Accumulate: Decide between saturation and wrapping if an overflow occurred.
            if (overflow && !overflow_wrap) begin
                // Saturation: Clamp to the maximum positive or maximum negative 2's complement value.
                acc_reg[WIDTH-1:0] <= acc_reg[WIDTH-1] ? {1'b1, {(WIDTH-1){1'b0}}} : {1'b0, {(WIDTH-1){1'b1}}};
            end else begin
                // Wrapping: Standard addition result.
                acc_reg[WIDTH-1:0] <= sum;
            end
        end
    end

endmodule
`endif
