name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttihp26a
        with:
          pdk: ihp-sg13g2
          librelane-version: 3.0.0.dev44

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttihp26a

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttihp26a

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: TinyTapeout/tt-gds-action/viewer@ttihp26a

  colorizer:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download GDS artifact
        uses: actions/download-artifact@v4
        with:
          name: tt_submission

      - name: Generate Colored Visualization
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libqt5widgets5 libqt5gui5 libqt5core5a libqt5xml5 libqt5network5 libqt5multimedia5 libqt5printsupport5 libqt5svg5 libqt5sql5 libqt5dbus5 libqt5test5 libxcb-xinerama0
          pip install klayout
          xvfb-run python3 gds_colorizer.py

      - name: Upload Colored Visualization
        uses: actions/upload-artifact@v4
        with:
          name: gds_colored_zones
          path: gds_colored_zones.png
